name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Ensure this matches your default branch name

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Waleed2207  # Hardcoded username to prevent undefined errors
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push generated SVGs to `output` branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan output
          git reset --hard
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "Updated GitHub Snake animation"
          git push -f origin output
